### ISSUE TITLE
Driver Version Pretty Old for install_gpy_driver.py

### ISSUE THREAD

**Issue by wenyhu-google** [GoogleCloudPlatform/compute-gpu-installation#24]
Google officially recommends https://raw.githubusercontent.com/GoogleCloudPlatform/compute-gpu-installation/main/linux/install_gpu_driver.py for GPU driver installation, ref in https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#installation_scripts, however, I feel the driver version update on this python is not that often. The current GPU driver versions the file uses is as below:
```
DRIVER_URL = "https://us.download.nvidia.com/tesla/525.85.12/NVIDIA-Linux-x86_64-525.85.12.run"
K80_DRIVER_URL = "https://us.download.nvidia.com/tesla/470.103.01/NVIDIA-Linux-x86_64-470.103.01.run"
```
Especially the K80_DRIVER_URL which is pretty old, even no longer supports standard Rocky Linux 8 images.

Can we update the driver version urls, and if possible, make some auto version update for those 2 lines?

Thanks.

**Comment by m-strzelczyk** [comment]
Hello @wenyhu-google !

First, let me explain the K80 version. Driver 470 is the last one supporting K80 GPUs. We simply cannot use a newer driver, as the newer drivers just no longer support K80s. That's why we're stuck with 470. [See note about K80 here](https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#minimum-driver).

As for the driver version for the other models - I'm trying to be careful with using the newest versions available, to avoid any compatibility issues. We once had a situation, when there were  problems when using the newest drivers with GCP GPUs. That's the main reason we don't pull the drivers from OS repositories or just download the newest version available.

The current version used here is `525.85.12`. It was released in January 2023, so it's around 6-months old.

If you have a reason to upgrade this to the newest (535) version, go ahead and send a PR - we can test things out and most likely just merge it. If not, I'll probably update the version in a couple of months or when someone asks me to do this :)

Cheers!

**Comment by wenyhu-google** [comment]
Thanks for your reply!

I think at least for 470 series, we need a newer version such as 470.199.02 (ref: https://pantheon.corp.google.com/storage/browser/nvidia-drivers-us-public/tesla). E.g. Now I cannot install GPU driver correctly with K80 on rocky-linux-8-v20230615 with https://raw.githubusercontent.com/GoogleCloudPlatform/compute-gpu-installation/main/linux/install_gpu_driver.py because the 470.103.01 does not support the newer kernel.

I know K80 is deprecated, but since customers can still use that now until 05/01/2024, my team still needs support K80 with different images now. Could you help update the K80 version to be 477.199.02?

Hope this makes sense to you, thanks again!

**Comment by m-strzelczyk** [comment]
The version has been updated:

* K80 to 470.199.02
* Everything else: 525.125.06

Let me know if you need another update like that.
